version: '3.4'

services:
  pnctapi:
    image: apiservice
    restart: always
    container_name: apiservice
    ports:
      - 5000:5000
      - 5001:5001
    build:
      context: .
      dockerfile: src/PlutoNetCoreTemplate/Dockerfile

  pnctjob:
    image: jobservice
    restart: always
    container_name: jobservice
    ports:
      - 5000:5000
      - 5001:5001
    build:
      context: .
      dockerfile: BackgroundJobs/PlutoNetCoreTemplate.Job.Hosting/Dockerfile
